# Generated by Django 3.2 on 2022-09-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_enabled',
            new_name='is_enable',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='is_enabled',
            new_name='is_enable',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_enabled',
            new_name='is_enable',
        ),
    ]
